env: "posggym"

env_args:
  key: "CooperativeReaching-v0"
  size: 10
  num_goals: 4
  mode: "original"
  time_limit: 100
  pretrained_wrapper: null

save_model: True
save_model_interval: 50000

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 1000000
